name: Build, Test, and Deploy

on: [push]
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          node-version: 14.x

      - name: Install
        run: npm install --legacy-peer-deps

      - name: Build
        run: |
          node --max-old-space-size=4096 `which npm` run build --if-present
        env:
          CI: true

      - name: Test
        run: |
          node --max-old-space-size=4096 `which npm` run ci --if-present
        env:
          CI: true

      - name: Prepare and deploy
        run: |
          npm run deploy-docs -- --name="Swimlane" --email="swimlane-devops@swimlane.com"
        if: ${{ github.ref == 'refs/heads/master' }}
        env:
          CI: true
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
